add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$line_break\
$hostname\
$character"""

[directory]
truncation_length = 0
truncate_to_repo = false
use_os_path_sep = false
format = "[$path]($style)"
style = "bold blue"

[directory.substitutions]
'C:\msys64\home\jasen' = '~'
'C:/msys64/home/jasen' = '~'

[hostname]
ssh_only = false
trim_at = ""
format = "[$hostname]($style) "
style = "bold cyan"

[character]
success_symbol = "[\u276F](bold green)"
error_symbol = "[\u276F](bold red)"

[git_branch]
format = " [$symbol$branch]($style)"
symbol = "\uE0A0 "
style = "bold purple"

[git_status]
format = " [$all_status$ahead_behind]($style)"
style = "bold red"

